// 集中式图标注册表：全应用唯一的图标事实来源。
// v2 起底层换用 @lucide/vue（树摇友好、24×24 线性、与暖纸描边风格一致）；
// 本文件只做"语义名 → lucide 组件"的 curated 映射，视图仍通过
// <UiIcon name="…" /> 取用，不直接 import lucide。
// 注意：lucide 新版改名 Filter→Funnel、CircleHelp→CircleQuestionMark。
import type { Component } from 'vue'
import {
  Activity,
  ArrowDown,
  ArrowRight,
  ArrowUpDown,
  ArrowUp,
  ArrowUpRight,
  Boxes,
  CalendarClock,
  ChartColumn,
  ChartLine,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  Clock,
  Command,
  Copy,
  CopyCheck,
  Cpu,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileClock,
  FileText,
  Funnel,
  Gauge,
  Globe,
  HeartPulse,
  Inbox,
  Info,
  KeyRound,
  KeySquare,
  Keyboard,
  Layers,
  Link2,
  List,
  Lock,
  LogOut,
  Menu,
  Moon,
  Network,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Play,
  Plus,
  PowerOff,
  Radio,
  RefreshCw,
  Rows3,
  Route,
  ScanSearch,
  ScrollText,
  Search,
  Server,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  SquarePen,
  Sun,
  Table,
  Terminal,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Upload,
  UserRound,
  Wallet,
  Waypoints,
  WifiOff,
  X,
  Zap,
} from '@lucide/vue'

export const icons = {
  // ── 导航 ──
  key: KeyRound,
  provider: Layers,
  model: Cpu,
  access: KeySquare,
  proxy: Network,
  system: ChartColumn,
  logout: LogOut,
  // ── 操作 ──
  plus: Plus,
  upload: Upload,
  play: Play,
  edit: SquarePen,
  trash: Trash2,
  refresh: RefreshCw,
  copy: Copy,
  'copy-check': CopyCheck,
  search: Search,
  filter: Funnel,
  sliders: SlidersHorizontal,
  download: Download,
  uploadCloud: Upload,
  externalLink: ExternalLink,
  // ── 状态与提示 ──
  check: Check,
  'check-circle': CircleCheck,
  warning: TriangleAlert,
  'info-circle': Info,
  'x-circle': CircleX,
  help: CircleQuestionMark,
  'wifi-off': WifiOff,
  pause: Pause,
  powerOff: PowerOff,
  // ── 观测域 ──
  pulse: Activity,
  bolt: Zap,
  shield: ShieldCheck,
  clock: Clock,
  timer: Timer,
  'calendar-clock': CalendarClock,
  server: Server,
  globe: Globe,
  chart: ChartLine,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  gauge: Gauge,
  database: Database,
  radio: Radio,
  heartbeat: HeartPulse,
  waypoints: Waypoints,
  route: Route,
  scan: ScanSearch,
  terminal: Terminal,
  history: FileClock,
  'scroll-text': ScrollText,
  'file-text': FileText,
  boxes: Boxes,
  wallet: Wallet,
  sparkles: Sparkles,
  // ── 通用 UI ──
  close: X,
  menu: Menu,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  sort: ArrowUpDown,
  table: Table,
  rows: Rows3,
  grid: List,
  link: Link2,
  lock: Lock,
  keyboard: Keyboard,
  more: Ellipsis,
  eye: Eye,
  'eye-off': EyeOff,
  settings: Settings,
  user: UserRound,
  inbox: Inbox,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  // ── 主题与命令面板 ──
  sun: Sun,
  moon: Moon,
  command: Command,
} as const satisfies Record<string, Component>

export type IconName = keyof typeof icons
