// 设计系统原语统一出口：视图从 shared/ui 一处取用全部基础组件。
export { default as UiBadge } from './UiBadge.vue'
export { default as UiButton } from './UiButton.vue'
export { default as UiCard } from './UiCard.vue'
export { default as UiConfirmDialog } from './UiConfirmDialog.vue'
export { default as UiCopyField } from './UiCopyField.vue'
export { default as UiEmptyState } from './UiEmptyState.vue'
export { default as UiField } from './UiField.vue'
export { default as UiIcon } from './UiIcon.vue'
export { default as UiInput } from './UiInput.vue'
export { default as UiKbd } from './UiKbd.vue'
export { default as UiMenu } from './UiMenu.vue'
export { default as UiModal } from './UiModal.vue'
export { default as UiPageHeader } from './UiPageHeader.vue'
export { default as UiProgressRing } from './UiProgressRing.vue'
export { default as UiSelect } from './UiSelect.vue'
export { default as UiSkeleton } from './UiSkeleton.vue'
export { default as UiStat } from './UiStat.vue'
export { default as UiStatCard } from './UiStatCard.vue'
export { default as UiStatePanel } from './UiStatePanel.vue'
export { default as UiSwitch } from './UiSwitch.vue'
export { default as UiTabs } from './UiTabs.vue'
export { default as UiTextarea } from './UiTextarea.vue'
export { default as UiTooltip } from './UiTooltip.vue'
export { icons, type IconName } from './icons'
export type { DataTableColumn } from './dataTable'
export type { UiTabItem } from './UiTabs.vue'
